### ISSUE TITLE
Craft 3.5.2 Deprecation Error: `enabledForSite` element query param has been deprecated

### ISSUE THREAD

**Issue by saltymouse** [sebastian-lenz/craft-linkfield#114]
After setting the link field to type "Entry" with custom text, the following error appears when saving the entry:

```
craft\errors\DeprecationException: The `enabledForSite` element query param has been deprecated. `status()` should be used instead. in /var/www/html/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php:225
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1024): craft\services\Deprecator->log('ElementQuery::e...', 'The `enabledFor...')
#1 /var/www/html/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php(225): craft\elements\db\ElementQuery->enabledForSite(false)
#2 /var/www/html/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php(76): lenz\linkfield\models\element\ElementLink->queryElement(false)
#3 /var/www/html/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php(146): lenz\linkfield\models\element\ElementLink->getElement(false)
#4 /var/www/html/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php(165): lenz\linkfield\models\element\ElementLink->hasElement()
#5 /var/www/html/vendor/sebastianlenz/craft-utils/src/foreignField/ForeignField.php(108): lenz\linkfield\models\element\ElementLink->isEmpty()
#6 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1745): lenz\craft\utils\foreignField\ForeignField->isValueEmpty(Object(lenz\linkfield\models\element\ElementLink), Object(verbb\supertable\elements\SuperTableBlockElement))
#7 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1437): craft\base\Element->isFieldEmpty('button')
#8 [internal function]: craft\base\Element->__call('isFieldEmpty:bu...', Array)
#9 /var/www/html/vendor/yiisoft/yii2/validators/Validator.php(470): call_user_func(Array, Object(lenz\linkfield\models\element\ElementLink))
#10 /var/www/html/vendor/yiisoft/yii2/validators/Validator.php(258): yii\validators\Validator->isEmpty(Object(lenz\linkfield\models\element\ElementLink))
#11 /var/www/html/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(verbb\supertable\elements\SuperTableBlockElement), Array)
#12 /var/www/html/vendor/verbb/super-table/src/fields/SuperTableField.php(785): yii\base\Model->validate()
#13 /var/www/html/vendor/craftcms/cms/src/base/Element.php(1730): verbb\supertable\fields\SuperTableField->validateBlocks(Object(craft\elements\Entry), NULL)
#14 /var/www/html/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:homeIntro', Array, Object(yii\validators\InlineValidator), Object(verbb\supertable\elements\db\SuperTableBlockQuery))
#15 /var/www/html/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:homeIntro')
#16 /var/www/html/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#17 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2208): yii\base\Model->validate()
#18 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(691): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, NULL)
#19 /var/www/html/vendor/craftcms/cms/src/controllers/EntriesController.php(380): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#20 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#23 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('save-entry', Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#25 /var/www/html/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('entries/save-en...', Array)
#26 /var/www/html/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction('entries/save-en...', Array)
#27 /var/www/html/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#28 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/www/html/web/index.php(22): yii\base\Application->run()
#30 {main}
```

The error prevents saving the new values.
Using the "URL" mode instead of "Entry" works.
It seems like the plugin is using a deprecated method. Any ideas?

`Craft: 3.5.2`
`Typed link field: 2.0.0-beta.9`

**Comment by sebastian-lenz** [comment]
Hi @saltymouse, thanks for reporting this. I've removed the call to `enabledForSite`.

**Comment by sebastian-lenz** [comment]
I've just releases version 2.0.0-beta.10 containing the fix.

**Comment by sebastian-lenz** [comment]
It's funny that the call to `ElementQuery::anyStatus()` performs the exact same action as the deprecated method `ElementQuery::enabledForSite` under the hood. But it is not marked as deprecated and I'll close this issue for now. If you encounter any other problems, please feel free to open a new issue.
