### ISSUE TITLE
Migrating from 1.0 to 2.0 bug

### ISSUE THREAD

**Issue by curtishenson** [sebastian-lenz/craft-linkfield#121]
Found maybe an edge case in the migration. I have two "phone" fields one is a plaintext and one is a linkfield. It looks like at some point I had the linkfield field in place of the plaintext field on an entry. So in the database there is a string entry of '555-555-5555' in the linkfield column, which causes the JSON decode error below.

I'm not sure why that field is even getting parsed since I don't believe it is an instance of LinkField. Maybe the `updateLinkField` function is grabbing it?

```
Exception: Syntax error. (/app/vendor/yiisoft/yii2/helpers/BaseJson.php:133)
#0 /app/vendor/yiisoft/yii2/helpers/BaseJson.php(107): yii\helpers\BaseJson::handleJsonError(4)
#1 /app/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(130): yii\helpers\BaseJson::decode('555-555-5555')
#2 /app/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(89): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateLinkField(Object(lenz\linkfield\fields\LinkField), '{{%content}}', 'field_')
#3 /app/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(53): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateField(Object(lenz\linkfield\fields\LinkField), '{{%content}}')
#4 /app/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(30): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateAllFields()
#5 /app/vendor/craftcms/cms/src/db/Migration.php(52): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->safeUp()
#6 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(lenz\linkfield\migrations\m190417_202153_migrateDataToTable))
#8 /app/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 /app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#10 /app/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /app/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#15 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /app/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#17 /app/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#18 /app/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /app/public/index.php(21): yii\base\Application->run()
#21 {main}
```

**Comment by sebastian-lenz** [comment]
When your delete and create fields in Craft, Craft should drop and freshly created the related columns in your database. So under normal circumstances no "old" data should be present in the column of a field. The link field always stores a chunk of json, so it's quite strange that we see the plain phone number here.

What are the names of the affected columns in the database? Do they have an unusual prefix?

**Comment by curtishenson** [comment]
The column names are `field_phone` and `field_phonePlain`. 

Noticed this is only in a single Channel and it looks like it only effects entries from the initial launch(only 2 new ones). So I'm assuming this is a missed migration or project config sync gone wrong.

I'll close this for now because I think it's probably a serious edge case. I have a grip of websites I'll be updating to 2.0 so I'll open again if I see it happen.
