### ISSUE TITLE
Invalid Configuration – Unable to locate message source for category 'typedlinkfield'.

### ISSUE THREAD

**Issue by daltonrooney** [sebastian-lenz/craft-linkfield#129]
I know someone posted a similar issue last year which was caused by another plugin. I've removed every plugin and and I'm still having the issue. 

Craft CMS 3.5.15.1
Typed-Linkfield 2.0.0-beta.7

Stacktrace:

```
yii\base\InvalidConfigException: Unable to locate message source for category 'typedlinkfield'. in /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/i18n/I18N.php:201
Stack trace:
#0 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\I18N->getMessageSource()
#1 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/i18n/I18N.php(321): yii\i18n\I18N->translate()
#2 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/BaseYii.php(538): craft\i18n\I18N->translate()
#3 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/sebastianlenz/linkfield/src/models/LinkType.php(101): yii\BaseYii::t()
#4 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(97): lenz\linkfield\models\LinkType->getTranslatedDisplayGroup()
#5 [internal function]: lenz\linkfield\fields\LinkField->lenz\linkfield\fields\{closure}()
#6 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(100): uasort()
#7 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(248): lenz\linkfield\fields\LinkField->getAvailableLinkTypes()
#8 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/base/Component.php(180): lenz\linkfield\fields\LinkField->setTypeSettings()
#9 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#10 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#11 [internal function]: yii\base\BaseObject->__construct()
#12 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs()
#13 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#14 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#15 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject()
#16 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/services/Fields.php(573): craft\helpers\Component::createComponent()
#17 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/services/Fields.php(598): craft\services\Fields->createField()
#18 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/services/Fields.php(627): craft\services\Fields->_fields()
#19 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2005): craft\services\Fields->getAllFields()
#20 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1360): craft\elements\db\ElementQuery->customFields()
#21 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#22 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#23 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand()
#24 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one()
#25 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1505): craft\db\Query->one()
#26 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/elements/User.php(413): craft\elements\db\ElementQuery->one()
#27 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/web/User.php(597): craft\elements\User::findIdentity()
#28 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/web/User.php(316): yii\web\User->getIdentityAndDurationFromCookie()
#29 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/web/User.php(709): yii\web\User->loginByCookie()
#30 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/web/User.php(485): yii\web\User->renewAuthStatus()
#31 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/web/User.php(194): craft\web\User->renewAuthStatus()
#32 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/web/Application.php(400): yii\web\User->getIdentity()
#33 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/src/web/Application.php(95): craft\web\Application->debugBootstrap()
#34 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#35 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct()
#36 [internal function]: yii\base\Application->__construct()
#37 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs()
#38 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#39 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#40 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject()
#41 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/craft/vendor/craftcms/cms/bootstrap/web.php(51): require('/home/hcps/weba...')
#42 /home/hcps/webapps/hcps-api-staging/releases/2916d363203d956bdcac2310f8afbf73f3e0821b/public/index.php(20): require('/home/hcps/weba...')
#43 {main}
```
Thanks for any help you can offer.

**Comment by sebastian-lenz** [comment]
Hi @daltonrooney, it looks like Craft has an issue fetching translations for a link field while loading the identity of the logged in user. I've just checked the program flow in my local installation and for me this works fine. As the stack trace does not show anything unusual, it basically just contains Craft CMS core and Yii code we need some additional information to tackle this problem.

The message source category 'typedlinkfield' is the plugin handle of this plugin and if you have activated the plugin in Craft it should be automatically available. So, is the plugin actually active in this project?

On a side note, I'm actually irritated to see this code of the plugin being called so early, in the program flow. While this might not resolve your actual problem, I've revised the way the plugin bootstraps and made the code run lazily when it is actually needed.

**Comment by daltonrooney** [comment]
Hi @sebastian-lenz, thanks for the help. Yes I'm sure the plugin is active in the project - I have it running successfully on my local dev machine. But when I deploy to the staging server I see this error.

Upgrading my install to linkfield:dev-master seems to have fixed the problem, so I think you're on the right track with https://github.com/sebastian-lenz/craft-linkfield/commit/c8d77aab8d6e5144b33ae91d9a13bdc85dc0757f. Thanks for looking into this!

**Comment by daltonrooney** [comment]
Well... I spoke too soon. The latest update does seem to have partially solved the problem, as the front end loads and so does the CP login form, but I'm still not able to log into the CP. 

The web.log does include one extra bit of information that may be helpful:

```
2020-11-23 14:01:44 [-][-][-][warning][application] Link field `getLinkTypes` called before the plugin has been loaded.
2020-11-23 14:01:44 [-][-][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Unable to locate message source for category 'typedlinkfield'. in /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/i18n/I18N.php:201
Stack trace:
#0 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\I18N->getMessageSource()
#1 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/i18n/I18N.php(321): yii\i18n\I18N->translate()
#2 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/BaseYii.php(538): craft\i18n\I18N->translate()
#3 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/sebastianlenz/linkfield/src/models/LinkType.php(101): yii\BaseYii::t()
#4 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(97): lenz\linkfield\models\LinkType->getTranslatedDisplayGroup()
#5 [internal function]: lenz\linkfield\fields\LinkField->lenz\linkfield\fields\{closure}()
#6 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(100): uasort()
#7 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/sebastianlenz/linkfield/src/fields/LinkField.php(248): lenz\linkfield\fields\LinkField->getAvailableLinkTypes()
#8 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/base/Component.php(180): lenz\linkfield\fields\LinkField->setTypeSettings()
#9 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#10 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#11 [internal function]: yii\base\BaseObject->__construct()
#12 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs()
#13 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#14 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#15 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject()
#16 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/services/Fields.php(573): craft\helpers\Component::createComponent()
#17 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/services/Fields.php(598): craft\services\Fields->createField()
#18 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/services/Fields.php(627): craft\services\Fields->_fields()
#19 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2005): craft\services\Fields->getAllFields()
#20 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1360): craft\elements\db\ElementQuery->customFields()
#21 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#22 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#23 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand()
#24 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one()
#25 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1505): craft\db\Query->one()
#26 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/services/Users.php(200): craft\elements\db\ElementQuery->one()
#27 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/controllers/UsersController.php(152): craft\services\Users->getUserByUsernameOrEmail()
#28 [internal function]: craft\controllers\UsersController->actionLogin()
#29 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#30 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#31 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#32 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#33 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#34 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#35 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#36 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#37 /home/hcps/webapps/hcps-api-staging/releases/d68f5773e2af09a2e54ed6b0e854c0e0041a99ce/public/index.php(21): yii\base\Application->run()
#38 {main}
```

**Comment by sebastian-lenz** [comment]
According to your stack trace, the method `getAvailableLinkTypes` gets called by `setTypeSettings`. However, thats one of the things I've changed (see https://github.com/sebastian-lenz/craft-linkfield/commit/c8d77aab8d6e5144b33ae91d9a13bdc85dc0757f#diff-8f6e0e56cd9d1b2f1357f6471ce4ae24d5ac48e641e069a10a6e9789ae0fd8a8L204), so are you sure you've updated to the latest version on master?

**Comment by daltonrooney** [comment]
Weird - I did update to the latest version on master, but running composer nuke fixed it so clearly something went wrong along the way. Sorry to bother you with another issue that's totally not your problem. 
https://twitter.com/nystudio107/status/1176180983982415872
