### ISSUE TITLE
Upgrading from v1 to v2 throws an error.

### ISSUE THREAD

**Issue by alexr8** [sebastian-lenz/craft-linkfield#141]
I tried upgrading from v1 to v2 at get this error when accessing my admin panel `Setting unknown property: typedlinkfield\fields\LinkField::allowedLinkNames`. I've included the stack trace that first got shown when I refreshed my admin after installing. I've tried clearing caches, but the CLI outputs the same error: `Error clearing cache Link field element cache: Setting unknown property: typedlinkfield\fields\LinkField::allowedLinkNames`

```
yii\base\UnknownPropertyException: Setting unknown property: typedlinkfield\fields\LinkField::allowedLinkNames in /app/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /app/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('allowedLinkName...', Array)
#1 /app/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(typedlinkfield\fields\LinkField), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /app/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#4 /app/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('typedlinkfield\\...', Array, Array)
#5 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('typedlinkfield\\...', Array, Array)
#6 /app/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject(Array)
#7 /app/vendor/craftcms/cms/src/services/Fields.php(573): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#8 /app/vendor/craftcms/cms/src/services/Fields.php(598): craft\services\Fields->createField(Array)
#9 /app/vendor/craftcms/cms/src/services/Fields.php(627): craft\services\Fields->_fields(NULL)
#10 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2031): craft\services\Fields->getAllFields()
#11 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1361): craft\elements\db\ElementQuery->customFields()
#12 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#13 /app/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#14 /app/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Query->createCommand(Object(craft\db\Connection))
#15 /app/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#16 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1515): craft\db\Query->one(NULL)
#17 /app/vendor/craftcms/cms/src/elements/User.php(428): craft\elements\db\ElementQuery->one()
#18 /app/vendor/yiisoft/yii2/web/User.php(692): craft\elements\User::findIdentity(1)
#19 /app/vendor/craftcms/cms/src/web/User.php(485): yii\web\User->renewAuthStatus()
#20 /app/vendor/yiisoft/yii2/web/User.php(194): craft\web\User->renewAuthStatus()
#21 /app/vendor/spacecatninja/imager-x/src/ImagerX.php(310): yii\web\User->getIdentity()
#22 /app/vendor/spacecatninja/imager-x/src/ImagerX.php(251): spacecatninja\imagerx\ImagerX->registerCacheOptions()
#23 [internal function]: spacecatninja\imagerx\ImagerX->spacecatninja\imagerx\{closure}(Object(yii\base\Event))
#24 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#25 /app/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#26 /app/vendor/craftcms/cms/src/services/Plugins.php(274): yii\base\Component->trigger('afterLoadPlugin...')
#27 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1431): craft\services\Plugins->loadPlugins()
#28 /app/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#29 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#30 /app/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#31 [internal function]: yii\base\Application->__construct(Array)
#32 /app/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#33 /app/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#34 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#35 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#36 /app/vendor/craftcms/cms/bootstrap/web.php(51): require('/app/vendor/cra...')
#37 /app/public/index.php(21): require('/app/vendor/cra...')
#38 {main}

**Comment by sebastian-lenz** [comment]
Hi @alexr8, sorry it took me so long to check on you, but I had to prepare a sample site to test the upgrade process. Could you explain how you did install the upgrade?

I guess you've upgraded your `composer.json` and have run `composer update`. In order to complete the upgrade process you must also apply the database migration, within your project folder you can run this command:

```shell
$ ./craft migrate/all
```

Once the plugin is available in the store Craft will run this command by default after downloading the update. For the time beeing we must trigger it manually.

**Comment by arthurdewolf** [comment]
I have this same issue on 2.0.0-beta.12 and need to add your 9fd90ac change of adding `public $allowedLinkNames = '*';` to LinkField.php to fix it. Running `migrate/all` doesn't fix it.
