### ISSUE TITLE
Custom fragment doesn't gets attached to element URL

### ISSUE THREAD

**Issue by gglnx** [sebastian-lenz/craft-linkfield#142]
Fragements used as custom query string on element URLs are currently ignored. If I comment out the `try/catch` in `ElementLink::getIntrinsicUrl()` the following error occurs:

```
yii\base\ErrorException: Undefined property: lenz\linkfield\models\Url::$query in vendor/sebastianlenz/craft-utils/src/models/Url.php:123
Stack trace:
#0 vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', 'vendor/sebastianle..., 123)
#1 vendor/sebastianlenz/craft-utils/src/models/Url.php(123): craft\web\ErrorHandler->handleError(8, 'Undefined prope...', 'vendor/sebastianle...', 123, Array)
#2 vendor/yiisoft/yii2/base/Component.php(140): lenz\craft\utils\models\Url->getQuery()
#3 vendor/yiisoft/yii2/base/Model.php(720): yii\base\Component->__get('query')
#4 vendor/yiisoft/yii2/base/Component.php(140): yii\base\Model->getAttributes()
#5 vendor/sebastianlenz/craft-utils/src/models/Url.php(79): yii\base\Component->__get('attributes')
#6 vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php(127): lenz\craft\utils\models\Url->__toString()
#7 vendor/sebastianlenz/linkfield/src/models/Link.php(351): lenz\linkfield\models\element\ElementLink->getIntrinsicUrl()
#8 vendor/twig/twig/src/Extension/CoreExtension.php(1507): lenz\linkfield\models\Link->getUrl()
#9 vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(lenz\linkfield\models\element\ElementLink), 'getUrl', Array, 'method', false, false)
#10 storage/runtime/compiled_templates
```

**Comment by mariohammel** [comment]
I migrated from 1.0.24 to 2.0.0-beta.12, applied the migration and receive the following error (Craft Version 3.6.5.1):

```
yii\base\ErrorException: Undefined property: lenz\linkfield\models\Url::$query in /var/www/html/vendor/sebastianlenz/craft-utils/src/models/Url.php:123
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', '/var/www/html/v...', 123)
#1 /var/www/html/vendor/sebastianlenz/craft-utils/src/models/Url.php(123): craft\web\ErrorHandler->handleError(8, 'Undefined prope...', '/var/www/html/v...', 123, Array)
#2 /var/www/html/vendor/yiisoft/yii2/base/Component.php(140): lenz\craft\utils\models\Url->getQuery()
#3 /var/www/html/vendor/yiisoft/yii2/base/Model.php(720): yii\base\Component->__get('query')
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(140): yii\base\Model->getAttributes()
#5 /var/www/html/vendor/sebastianlenz/craft-utils/src/models/Url.php(79): yii\base\Component->__get('attributes')
#6 /var/www/html/vendor/sebastianlenz/linkfield/src/models/element/ElementLink.php(126): lenz\craft\utils\models\Url->__toString()
#7 /var/www/html/vendor/sebastianlenz/linkfield/src/models/Link.php(351): lenz\linkfield\models\element\ElementLink->getIntrinsicUrl()
#8 /var/www/html/vendor/sebastianlenz/linkfield/src/models/Link.php(270): lenz\linkfield\models\Link->getUrl(NULL)
#9 /var/www/html/vendor/sebastianlenz/linkfield/src/models/Link.php(218): lenz\linkfield\models\Link->getRawLinkAttributes(NULL)
#10 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1507): lenz\linkfield\models\Link->getLink()
#11 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(lenz\linkfield\models\element\ElementLink), 'getLink', Array, 'method', false, false)
#12 /var/www/html/storage/runtime/compiled_templates/03/032883f6745934d000b2c1010a2dcfb6082ecc066fba2ac11a235a7f3d2ced21.php(77): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(lenz\linkfield\models\element\ElementLink), 'getLink', Array, 'method')
#13 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e1091ee8dcff53eb07690deef64988c72b1712bf835bd8205078d1bd50d40d0c->doDisplay(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/7f/7f24c63d3a6537f8af10720379b1fc88c4ce5736d49bf4b0bc05981b7ee9bd39.php(54): Twig\Template->display(Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8163d6f0bfb49ec70f26791fc40b226eca2868c71563b06ab67dd0a9963cffe2->doDisplay(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/storage/runtime/compiled_templates/95/9556d625a57afcc9002a222d599d5b1c90a7fa2a23e7ab601b264219f253a991.php(52): Twig\Template->display(Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_32cc7f0ec8dfb0ad68f5f85e4bcb9745030d0293d20c027bee5c6432cb6d5fd7->doDisplay(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/storage/runtime/compiled_templates/cd/cd3670654021e56efdf3a42a0bf3897d03245de1f3c720802cb893ea1120b3fa.php(43): Twig\Template->display(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_cc4e8fcee4b4c33465ebec96a265b2ab67ffa00ff6227bc41a1cef98efd22a35->doDisplay(Array, Array)
#23 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#25 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#26 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#27 /var/www/html/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('index', Array)
#28 /var/www/html/vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate('index', Array)
#29 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('index', Array, 'site')
#30 /var/www/html/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('index', Array)
#31 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#32 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#34 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#35 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#36 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#37 /var/www/html/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#38 /var/www/html/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#39 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#40 /var/www/html/web/index.php(21): yii\base\Application->run()
#41 {main}
```

If I comment out the foreach block in `src/models/Url.php:123`, the error disappears.

**Comment by sebastian-lenz** [comment]
Okay, I've fixed an issue that was caused by unsetting attributes on the Url model. The fix will be part of the next release, but I have to take a look at the upgrade issues first. If you need the fix right now, please switch the version requirement in your `composer.json` to `dev-master`

**Comment by gglnx** [comment]
Looks good. Thank you!

**Comment by sebastian-lenz** [comment]
Thanks for the feedback!
