### ISSUE TITLE
Migration failed in Craft 3.7+ (from 1.0.25 to 2.0.0-rc1)

### ISSUE THREAD

**Issue by alexroper** [sebastian-lenz/craft-linkfield#164]
It looks like Craft changed how fields are named in v3.7:

https://craftcms.com/knowledge-base/upgrading-to-craft-3-7#randomized-database-column-names

> Randomized Database Column Names
> Any new fields you create in Craft 3.7 will get a random string appended to their database column name. For example, instead of field_text, you’d get something like field_text_abcdefgh. This helps avoid potential column name conflicts that arose from time to time. If you have any code that is making assumptions about a field’s column name, you will need to adjust it accordingly. (The random column suffix can be obtained from the field’s columnSuffix setting.)

I'm getting this error when I try to upgrade from Link Field v1.0.25 to v2.0.0-rc1:

``` 
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_disclaimerButtonCta' in 'field list'
The SQL being executed was: SELECT `elementId`, `siteId`, `field_disclaimerButtonCta`
FROM `content` (/Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT `element...')
#1 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT `element...')
#2 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /Users/alexroper/Sites/curf/craft/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#5 /Users/alexroper/Sites/curf/craft/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(129): craft\db\Query->all()
#6 /Users/alexroper/Sites/curf/craft/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(90): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateLinkField(Object(lenz\linkfield\fields\LinkField), '{{%content}}', '')
#7 /Users/alexroper/Sites/curf/craft/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(54): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateField(Object(lenz\linkfield\fields\LinkField), '{{%content}}')
#8 /Users/alexroper/Sites/curf/craft/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(31): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateAllFields()
#9 /Users/alexroper/Sites/curf/craft/vendor/craftcms/cms/src/db/Migration.php(52): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->safeUp()
#10 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): craft\db\Migration->up()
#11 /Users/alexroper/Sites/curf/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(379): yii\console\controllers\BaseMigrateController->migrateUp('m190417_202153_...')
#12 [internal function]: craft\console\controllers\MigrateController->actionAll()
#13 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#15 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#16 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#17 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#18 /Users/alexroper/Sites/curf/craft/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#19 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#20 /Users/alexroper/Sites/curf/craft/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /Users/alexroper/Sites/curf/craft/craft(27): yii\base\Application->run()
#22 {main}
*** failed to apply m190417_202153_migrateDataToTable (time: 0.062s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

Seems like it might be looking for a field named `field_disclaimerButtonCta` but that column is actually `field_disclaimerButtonCta_salcusfi`.

Craft Pro 3.7.7
PHP: 7.3.27
MySQL: 5.5.5
Typed link field: 1.0.25

**Comment by magicspon** [comment]
I've managed to install it on a new project.  I had to remove all the existing link fields first.

Seeing this in the Deprecation Warnings:

```
Message:

Using of the legacy link field class is deprecated. The project configuration might need a rebuild, see https://github.com/sebastian-lenz/craft-linkfield/issues/122

Origin: /home/vagrant/dev/clients/healthwave/healthwave-cms/vendor/composer/ClassLoader.php:480
```

Craft Pro 3.7.7
PHP: 7.4.11
MySQL: 8.0.21
Typed link field: 2.0.0-rc1

**Comment by ajoliveau** [comment]
This problem still exists and isn't patched. I can confirm that this change fixes it. 
I opened a PR with the fix : https://github.com/sebastian-lenz/craft-linkfield/pull/186
