### ISSUE TITLE
Linking to Asset is Broken

### ISSUE THREAD

**Issue by RitterKnightCreative** [sebastian-lenz/craft-linkfield#21]
Getting a file not found.

It looks like only the file name (instead of the whole file path) is getting passed in. Thought it might have been my asset settings, tried an absolute path as well instead but still no dice.

Stack Trace:

```
yii\base\ErrorException: finfo_file(Aglime-Key-to-Increased-Yield-and-Profits1.pdf): failed to open stream: No such file or directory in /Volumes/ProBeast/Users/dave/Sites/W/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:158
Stack trace:
#0 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'finfo_file(Agli...', '/Volumes/ProBea...', 158)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'finfo_file(Agli...', '/Volumes/ProBea...', 158, Array)
#2 /Volumes/ProBeast/Users/dave/Sites/W/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(158): finfo_file(Resource id #468, 'Aglime-Key-to-I...')
#3 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/helpers/FileHelper.php(260): yii\helpers\BaseFileHelper::getMimeType('Aglime-Key-to-I...', NULL, true)
#4 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/helpers/FileHelper.php(308): craft\helpers\FileHelper::getMimeType('Aglime-Key-to-I...', NULL, true)
#5 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/elements/Asset.php(708): craft\helpers\FileHelper::isGif('Aglime-Key-to-I...')
#6 /Volumes/ProBeast/Users/dave/Sites/W/vendor/sebastianlenz/linkfield/src/models/ElementLinkType.php(206): craft\elements\Asset->getUrl()
#7 /Volumes/ProBeast/Users/dave/Sites/W/vendor/sebastianlenz/linkfield/src/models/Link.php(191): typedlinkfield\models\ElementLinkType->getUrl(Object(typedlinkfield\models\Link))
#8 /Volumes/ProBeast/Users/dave/Sites/W/vendor/sebastianlenz/linkfield/src/models/Link.php(214): typedlinkfield\models\Link->getUrl()
#9 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/helpers/StringHelper.php(758): typedlinkfield\models\Link->__toString()
#10 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/base/Field.php(337): craft\helpers\StringHelper::toString(Object(typedlinkfield\models\Link), ' ')
#11 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/fields/Matrix.php(555): craft\base\Field->getSearchKeywords(Object(typedlinkfield\models\Link), Object(craft\elements\Entry))
#12 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/services/Content.php(236): craft\fields\Matrix->getSearchKeywords(Object(craft\elements\db\MatrixBlockQuery), Object(craft\elements\Entry))
#13 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/services/Content.php(201): craft\services\Content->_updateSearchIndexes(Object(craft\elements\Entry), Object(craft\models\FieldLayout))
#14 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/services/Elements.php(459): craft\services\Content->saveContent(Object(craft\elements\Entry))
#15 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/controllers/EntriesController.php(543): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#16 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#17 /Volumes/ProBeast/Users/dave/Sites/W/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /Volumes/ProBeast/Users/dave/Sites/W/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('save-entry', Array)
#20 /Volumes/ProBeast/Users/dave/Sites/W/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#21 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('entries/save-en...', Array)
#22 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('entries/save-en...', Array)
#23 /Volumes/ProBeast/Users/dave/Sites/W/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /Volumes/ProBeast/Users/dave/Sites/W/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /Volumes/ProBeast/Users/dave/Sites/W/public_html/index.php(21): yii\base\Application->run()
#26 {main}
```

**Comment by sebastian-lenz** [comment]
This is a bug in Craft core. I've opened an issue over there: 
https://github.com/craftcms/cms/issues/2887

**Comment by RitterKnightCreative** [comment]
Thanks - up the chain it goes, ;)
