### ISSUE TITLE
Cannot update to 2.0.0-beta.6

### ISSUE THREAD

**Issue by ccchapman** [sebastian-lenz/craft-linkfield#77]
# Description

I am updating from 1.0.19 to 2.0.0-beta.6 running Craft 3.3.7. My database migrations fail.

I also tried deleting my (SuperTable) field that contains a link field.

# Steps to reproduce

1. Update plugin through composer (see console output below)
2. Visit CP and run migration
3. Migration fails (see stack trace below)

```
> composer require sebastianlenz/linkfield:"^2.0.0@beta"
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 1 update, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing sebastianlenz/craft-utils (2.2.3): Downloading (100%)
  - Updating sebastianlenz/linkfield (1.0.19 => 2.0.0-beta.6): Downloading (100%)
Writing lock file
Generating optimized autoload files
```

```
 2019-10-08 14:49:33 [-][-][-][error][craft\db\MigrationManager::migrateUp] Failed to apply m190417_202153_migrateDataToTable (time: 0.120s). Output:
     > update in {{%fields}} ... done (time: 0.009s)
     > update in {{%fields}} ... done (time: 0.000s)
 Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_linkSource' in 'field list'
 The SQL being executed was: SELECT `elementId`, `siteId`, `field_linkSource`
 FROM `craft_content` (/home/vagrant/redacted/vendor/yiisoft/yii2/db/Schema.php:664)
 #0 /home/vagrant/redacted/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `element...')
 #1 /home/vagrant/redacted/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `element...')
 #2 /home/vagrant/redacted/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
 #3 /home/vagrant/redacted/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
 #4 /home/vagrant/redacted/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
 #5 /home/vagrant/redacted/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(66): craft\db\Query->all()
 #6 /home/vagrant/redacted/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(48):                                                  lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateFieldInstance(Object(lenz\linkfield\fields\LinkField))
 #7 /home/vagrant/redacted/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(27):                                                  lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateFieldInstances()
 #8 /home/vagrant/redacted/vendor/craftcms/cms/src/db/Migration.php(56): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->safeUp()
 #9 /home/vagrant/redacted/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
 #10 /home/vagrant/redacted/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager-                                                         >migrateUp(Object(lenz\linkfield\migrations\m190417_202153_migrateDataToTable))
 #11 /home/vagrant/redacted/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
 #12 /home/vagrant/redacted/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
 #13 /home/vagrant/redacted/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-  db')
 #14 [internal function]: craft\controllers\UpdaterController->actionMigrate()
 #15 /home/vagrant/redacted/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
 #16 /home/vagrant/redacted/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
 #17 /home/vagrant/redacted/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
 #18 /home/vagrant/redacted/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
 #19 /home/vagrant/redacted/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
 #20 /home/vagrant/redacted/vendor/craftcms/cms/src/web/Application.php(653): craft\web\Application->runAction('updater/migrate')
 #21 /home/vagrant/redacted/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
 #22 /home/vagrant/redacted/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
 #23 /home/vagrant/redacted/web/index.php(21): yii\base\Application->run()
 #24 {main}

 2019-10-08 14:49:33 [-][-][-][error][craft\db\MigrationManager::up] Migration failed. The rest of the migrations are cancelled.
```

Related to #75.

**Comment by dangayle** [comment]
Similar/same issue:
```Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_button' in 'field list'
The SQL being executed was: SELECT elementId, siteId, field_button
FROM content

Migration: lenz\linkfield\migrations\m190417_202153_migrateDataToTable

Output:

> update in {{%fields}} ... done (time: 0.002s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
> update in {{%fields}} ... done (time: 0.000s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_button' in 'field list'
The SQL being executed was: SELECT elementId, siteId, field_button
FROM content (/Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT element...')
#1 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT element...')
#2 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /Users/dangayle/code/com.helloalpha.membership/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(66): craft\db\Query->all()
#6 /Users/dangayle/code/com.helloalpha.membership/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(48): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateFieldInstance(Object(lenz\linkfield\fields\LinkField))
#7 /Users/dangayle/code/com.helloalpha.membership/vendor/sebastianlenz/linkfield/src/migrations/m190417_202153_migrateDataToTable.php(27): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->updateFieldInstances()
#8 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/db/Migration.php(56): lenz\linkfield\migrations\m190417_202153_migrateDataToTable->safeUp()
#9 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#10 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(lenz\linkfield\migrations\m190417_202153_migrateDataToTable))
#11 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#12 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#13 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#14 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#15 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#18 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#19 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#20 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/web/Application.php(653): craft\web\Application->runAction('updater/migrate')
#21 /Users/dangayle/code/com.helloalpha.membership/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#22 /Users/dangayle/code/com.helloalpha.membership/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /Users/dangayle/code/com.helloalpha.membership/web/index.php(21): yii\base\Application->run()
#24 {main}```

**Comment by sebastian-lenz** [comment]
@dangayle Is the link field "button" also placed inside a "Super Table" field?

**Comment by dangayle** [comment]
@sebastian-lenz As far as I know, I have no field called button. Perhaps in an earlier iteration, but not now.

**Comment by Toni-hr98** [comment]
I had the same issue, you have to delete all previous buttons in your DB (tablename: fields), then the update will work

**Comment by jamesether** [comment]
> @dangayle Is the link field "button" also placed inside a "Super Table" field?

@sebastian-lenz I have the same issue, and I do have fields called `button` within Super Tables. Am I going to have to run through and rename all of my fields in order to run the migration?

**Comment by jamesether** [comment]
@sebastian-lenz I had success with changing the handles of all `button` fields that are within Super Tables.

**Comment by daltonrooney** [comment]
This still seems to be a common issue - I'm experiencing it across two sites as I'm trying to upgrade to Craft 3.7 and Typed Link Field 2.0.0-rc1.  I've tried changing the handles of my fields within the super table block as well as removing the fields altogether and re-running the migration with no luck. @sebastian-lenz Any thoughts on a solution?
